server:
  port: ${port:8088}
  use-forward-headers: true
  tomcat:
    protocol-header: X-FORWARDED-PROTO
    remote-ip-header: X-FORWARDED-FOR
    port-header: X-Forwarded-Port
    max-threads: 100
spring:
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: threedService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/threed_service?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: hz
    password: 123456
    initSize: 20
    minIdle: 20
    maxActive: 100
    # 使用druid数据源
 #   type: com.alibaba.druid.pool.DruidDataSource
 #   driver-class-name: com.mysql.jdbc.Driver
 #   filters: stat
 #   maxActive: 20
 #   initialSize: 1
  #  maxWait: 60000
  #  minIdle: 1
 #   timeBetweenEvictionRunsMillis: 60000
 #   minEvictableIdleTimeMillis: 300000
 #   validationQuery: select 'x'
 #   testWhileIdle: true
 #   testOnBorrow: false
 #   testOnReturn: false
 #   poolPreparedStatements: true
  #  maxOpenPreparedStatements: 20
   

 
 
